// This code automatically generated by TableCodeGen

using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;

[ExecuteAlways]
public static class FantasyDialogueTable
{

	private static string _pathToLoadCsv = "CSV/FantasyDialogue";
	private static TextAsset _currentCsv;

	public class Row
	{
		public string idLng;
		public string FR;
		public string EN;
	}

	static List<Row> rowList = new List<Row>();
	static bool isLoaded = false;
	
	public static bool IsLoaded()
	{
		return isLoaded;
	}

	public static List<Row> GetRowList()
	{
		return rowList;
	}

	private static TextAsset GetCsvFromFile()
	{
		TextAsset csv = Resources.Load<TextAsset>(_pathToLoadCsv);
		return csv;
	}

	public static void Load()
	{

		_currentCsv = GetCsvFromFile();
		if (_currentCsv !=  null)
		{
			Debug.Log($"CURRENT CSV FOUND : {_currentCsv.text}");
		}else
		{
			Debug.Log($"CURRENT CSV NOT FOUND");
                return;
        }
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(_currentCsv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.idLng = grid[i][0];
			row.FR = grid[i][1];
			row.EN = grid[i][2];

			rowList.Add(row);
			Debug.Log($"ADD ROW {rowList.Count}");

		}
		isLoaded = true;
	}

	public static int NumRows()
	{
		return rowList.Count;
	}

	public static Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public static Row Find_idLng(string find)
	{
		return rowList.Find(x => x.idLng == find);
	}
	public static List<Row> FindAll_idLng(string find)
	{
		return rowList.FindAll(x => x.idLng == find);
	}
	public static Row Find_FR(string find)
	{
		return rowList.Find(x => x.FR == find);
	}
	public static List<Row> FindAll_FR(string find)
	{
		return rowList.FindAll(x => x.FR == find);
	}
	public static Row Find_EN(string find)
	{
		return rowList.Find(x => x.EN == find);
	}
	public static List<Row> FindAll_EN(string find)
	{
		return rowList.FindAll(x => x.EN == find);
	}

	public static List<string> FindAll_Keys()
	{
		List<string> keys = new List<string>();
   
		foreach (Row row in rowList)
		{
			keys.Add(row.idLng);
		}

		return keys;
	}
}